eshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls'))
]

main/urls.py
from django.urls import path
from main.views import show_main, add_order_entry, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_order, delete_order, add_order_entry_ajax, create_mood_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add_order_entry/', add_order_entry, name='add_order_entry'),
    path('add-order-entry-ajax', add_order_entry_ajax, name='add_order_entry_ajax'),
    path('edit-order/<uuid:id>', edit_order, name='edit_order'),
    path('delete/<uuid:id>', delete_order, name='delete_order'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('create-flutter/', create_mood_flutter, name='create_mood_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %}
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/navbar.html
<nav class="bg-gray-900 shadow-lg fixed top-0 left-0 z-40 w-screen">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">

          <div class="text-2xl flex items-center font-bold text-white">
              E-Shop
          </div>

          <div class="hidden md:flex justify-center flex-grow">
              {% if user.is_authenticated %}
                  <a href="{% url 'main:show_main' %}" class="text-center text-gray-400 text-xl py-2 px-4 hover:text-gray-50">
                      Home
                  </a>
                  <a class="text-center text-gray-400 text-xl py-2 px-4 hover:text-gray-50">
                      Products
                  </a>
                  <a class="text-center text-gray-400 text-xl py-2 px-4 hover:text-gray-50">
                      Categories
                  </a>
                  <a class="text-center text-gray-400 text-xl py-2 px-4 hover:text-gray-50">
                      Cart
                  </a>
              {% endif %}
          </div>

          <div class="hidden md:flex">
              {% if user.is_authenticated %}
                  <span class="text-gray-400 m-auto mx-3">Welcome, {{ user.username }}</span>
                  <a href="{% url 'main:logout' %}" class="text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
                      Logout
                  </a>
              {% else %}
                  <a href="{% url 'main:login' %}" class="text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mr-2">
                      Login
                  </a>
                  <a href="{% url 'main:register' %}" class="text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
                      Register
                  </a>
              {% endif %}
          </div>

          <!-- Hamburger Button -->
          <button class="md:hidden flex items-center p-2 text-gray-400 hover:text-white focus:outline-none mobile-menu-button" aria-label="Toggle navigation">
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
              </svg>
          </button>
      </div>
  </div>

  <!-- Mobile Menu -->
  <div class="mobile-menu hidden md:hidden bg-gray-900 text-white px-4 w-full">
      {% if user.is_authenticated %}
      <div class="pt-2 pb-3 space-y-1 mx-auto">
          <a href="{% url 'main:show_main' %}" class="block py-2 px-4 hover:bg-gray-700">Home</a>
          <a class="block py-2 px-4 hover:bg-gray-700">Products</a>
          <a class="block py-2 px-4 hover:bg-gray-700">Categories</a>
          <a class="block py-2 px-4 hover:bg-gray-700">Cart</a>
          <span class="block text-gray-400 px-3 py-2">Welcome, {{ user.username }}</span>
          <a href="{% url 'main:logout' %}" class="block text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">
              Logout
          </a>
      </div>
      {% else %}
      <div class="pt-2 pb-3 space-y-1 mx-auto">
          <a href="{% url 'main:login' %}" class="block text-center bg-gray-900 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded mb-2">
              Login
          </a>
          <a href="{% url 'main:register' %}" class="block text-center bg-gray-900 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
              Register
          </a>
      </div>
      {% endif %}
  </div>

  <script>
      const btn = document.querySelector("button.mobile-menu-button");
      const menu = document.querySelector(".mobile-menu");

      btn.addEventListener("click", () => {
          menu.classList.toggle("hidden");
      });
  </script>
</nav>